-- ===================================================================
-- HYBITS CRM — Secure Storage RLS Policies for Multi-Tenant Isolation
-- Implements outlet-aware access control for storage buckets
-- ===================================================================

-- 1. Ensure buckets exist (idempotent)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('inventory-images', 'inventory-images', false, 52428800, ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp'])
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('documents', 'documents', false, 52428800, ARRAY['application/pdf', 'image/jpeg', 'image/png', 'text/plain'])
ON CONFLICT (id) DO NOTHING;

-- 2. Drop overly-permissive existing policies (idempotent)
DROP POLICY IF EXISTS "Allow authenticated read inventory images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated insert inventory images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated update inventory images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated delete inventory images" ON storage.objects;
DROP POLICY IF EXISTS "Users can read documents" ON storage.objects;
DROP POLICY IF EXISTS "Service role can manage documents" ON storage.objects;

-- 3. Inventory images policies: outlet-aware access control
-- File path structure expected: {outlet_id}/{item_code}/{filename}

CREATE POLICY "Inventory images outlet isolation - select" ON storage.objects
  FOR SELECT USING (
    bucket_id = 'inventory-images'
    AND (
      EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.id = auth.uid()
        AND (
          up.role = 'admin' OR 
          up.outlet_id::text = split_part(name, '/', 1)
        )
      )
    )
  );

CREATE POLICY "Inventory images outlet isolation - insert" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'inventory-images'
    AND (
      EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.id = auth.uid()
        AND (
          up.role = 'admin' OR 
          up.outlet_id::text = split_part(name, '/', 1)
        )
      )
    )
  );

CREATE POLICY "Inventory images outlet isolation - update" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'inventory-images'
    AND (
      EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.id = auth.uid()
        AND (
          up.role = 'admin' OR 
          up.outlet_id::text = split_part(name, '/', 1)
        )
      )
    )
  ) WITH CHECK (
    bucket_id = 'inventory-images'
    AND (
      EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.id = auth.uid()
        AND (
          up.role = 'admin' OR 
          up.outlet_id::text = split_part(name, '/', 1)
        )
      )
    )
  );

CREATE POLICY "Inventory images outlet isolation - delete" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'inventory-images'
    AND (
      EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.id = auth.uid()
        AND (
          up.role = 'admin' OR 
          up.outlet_id::text = split_part(name, '/', 1)
        )
      )
    )
  );

-- 4. Documents (PDFs) policies: invoice ownership-based access control
-- Only allow reading PDFs if the invoice belongs to user's outlet or user is admin

CREATE POLICY "Documents access by invoice ownership - select" ON storage.objects
  FOR SELECT USING (
    bucket_id = 'documents'
    AND (
      EXISTS (
        SELECT 1 FROM public.invoices i
        JOIN public.user_profiles up ON up.id = auth.uid()
        WHERE i.invoice_pdf_key = name
          AND (
            up.role = 'admin' OR 
            i.outlet_id = up.outlet_id
          )
      )
    )
  );

-- 5. Documents write access: only service role or admin functions
-- Normal users cannot write to documents bucket (PDFs generated by service)

CREATE POLICY "Documents insert by service" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'documents'
    AND (
      auth.role() = 'service_role' OR
      EXISTS (
        SELECT 1 FROM public.user_profiles up 
        WHERE up.id = auth.uid() 
        AND up.role = 'admin'
      )
    )
  );

CREATE POLICY "Documents update by service" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'documents'
    AND (
      auth.role() = 'service_role' OR
      EXISTS (
        SELECT 1 FROM public.user_profiles up 
        WHERE up.id = auth.uid() 
        AND up.role = 'admin'
      )
    )
  ) WITH CHECK (
    bucket_id = 'documents'
    AND (
      auth.role() = 'service_role' OR
      EXISTS (
        SELECT 1 FROM public.user_profiles up 
        WHERE up.id = auth.uid() 
        AND up.role = 'admin'
      )
    )
  );

CREATE POLICY "Documents delete by service" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'documents'
    AND (
      auth.role() = 'service_role' OR
      EXISTS (
        SELECT 1 FROM public.user_profiles up 
        WHERE up.id = auth.uid() 
        AND up.role = 'admin'
      )
    )
  );

-- 6. Grant necessary permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON storage.objects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON storage.buckets TO authenticated;

-- End of 011_secure_storage_rls_policies.sql
